version: "2"
services:
 app:
   container_name: app
   restart: always
   build: .
   ports:
     - "3000:3000"
   links:
     - cassandraDb
 cassandraDb:
   container_name: cassandraDb
   image: cassandraDb
   volumes:
     - ./data:/data/db
   ports:
     - "7199:7199"
     - "7000:7000"
     - "9042:9042"
     - "9160:9160"
     - "7001:7001"